#!/bin/sh
#Configurations injected by install_server below....
#/data/scripts/init.d/redis 
EXEC=/usr/local/redis/bin/redis-server
CLIEXEC=/usr/local/redis/bin/redis-cli
PIDFILE=/data/redis/redis.pid
CONF="/etc/redis.conf"
REDISPORT="6379"
###############
# SysV Init Information
# chkconfig: - 58 74
# description: redis_6379 is the redis daemon.
### BEGIN INIT INFO
# Provides: redis_6379
# Required-Start: $network $local_fs $remote_fs
# Required-Stop: $network $local_fs $remote_fs
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Should-Start: $syslog $named
# Should-Stop: $syslog $named
# Short-Description: start and stop redis_6379
# Description: Redis daemon
### END INIT INFO


case "$1" in
    start)
        if [ -f $PIDFILE ]
        then
            echo "$PIDFILE exists, process is already RUNNING or crashed"
        else
            echo "Starting Redis server..."
            $EXEC $CONF
        fi
        ;;
    stop)
        if [ ! -f $PIDFILE ]
        then
            echo "$PIDFILE does not exist, process is not RUNNING"
        else
            PID=$(cat $PIDFILE)
            echo "STOPPING ..."
            $CLIEXEC -p $REDISPORT -a "SBMTMnqd" shutdown
            while [ -x /proc/${PID} ]
            do
                echo "Waiting for Redis to shutdown ..."
                sleep 1
            done
            echo "Redis STOPPED"
        fi
        ;;
    status)
        PID=$(cat $PIDFILE)
        if [ ! -x /proc/${PID} ]
        then
            echo 'Redis is not RUNNING'
        else
            echo "Redis is RUNNING ($PID)"
        fi
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    version)
	echo 'Version:' `$EXEC --version|awk -F ' ' '{print $3}'|awk -F '=' '{print $2}'`
	;;
    *)
        echo "Please use start, stop, restart or status as first argument"
        ;;
esac

